"""Create package_versions table and add relations

Revision ID: 96cd5e692107
Revises: 4c50e2eae3ac
Create Date: 2025-10-09 10:14:45.414483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96cd5e692107'
down_revision: Union[str, Sequence[str], None] = '4c50e2eae3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('release', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('package_metadata', sa.JSON(), nullable=True),
    sa.Column('git_tag', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'version', 'release', name='_package_version_release_uc')
    )
    with op.batch_alter_table('package_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_versions_package_id'), ['package_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_versions_package_id'))
        batch_op.drop_index(batch_op.f('ix_package_versions_id'))

    op.drop_table('package_versions')
    # ### end Alembic commands ###
